### ISSUE TITLE
about CEQ metric

### ISSUE THREAD

**Issue by northsky0307** [Waste-Wood/e-CARE#1]
Hi, excited to see such an interesting new dataset. There are some questions about the evaluation metric CEQ.
the CEQ score has a significant positive relationship with the human evaluation results. but I didn't find the corresponding section in the code，nor in the leaderboard[leaderboard](https://scir-sp.github.io/).
where can i find the CEQ metric.

**Comment by Waste-Wood** [comment]
> Hi, excited to see such an interesting new dataset. There are some questions about the evaluation metric CEQ. the CEQ score has a significant positive relationship with the human evaluation results. but I didn't find the corresponding section in the code，nor in the leaderboard[leaderboard](https://scir-sp.github.io/). where can i find the CEQ metric.

Thank you for your interest in our dataset. We will upload the evaluation script and relevant data of CEQ metric in the next few days.

**Comment by sherryzyh** [comment]
Hi, thanks for your exciting work!
Where can I find the CEQ metric now? I still can't find the corresponding script or results.

**Comment by Waste-Wood** [comment]
Sorry about that, we will upload the code and data by next week.

**Comment by Waste-Wood** [comment]
Sorry for the delay.
We have uploaded the CEQ metric script, refer to https://github.com/Waste-Wood/e-CARE/tree/main/CEQ
Thanks for following our work.
